# Scaladoc configuration docs:
# https://scalameta.org/scalafmt/docs/configuration.html

# https://github.com/scalameta/scalafmt/releases
version = 3.9.10
runner.dialect = scala3

project.excludePaths = [
  "glob:**.sbt",
  "glob:**/keymaerax-webui/src/test/scala/org/keymaerax/btactics/Robix.scala"
]

maxColumn = 120

# Alignment
align.preset = none
align.stripMargin = true
assumeStandardLibraryStripMargin = true

# Newlines
newlines.source = fold
newlines.selectChains = unfold
newlines.ignoreInSyntax = false

# Rewrite rules
rewrite.rules = [Imports, SortModifiers]
rewrite.imports.sort = original
rewrite.trailingCommas.style = multiple
rewrite.sortModifiers.preset = styleGuide

# Comment processing
docstrings.style = Asterisk
docstrings.oneline = fold
docstrings.wrap = fold
