/**
  * Copyright (c) Carnegie Mellon University.
  * See LICENSE.txt for the conditions of this license.
  */
/**
  * @note Code Review 2016-08-02 LemmaDB aspects only
  */
package edu.cmu.cs.ls.keymaerax.hydra

import java.io.{File, FileOutputStream}
import java.nio.channels.Channels
import java.security.SecureRandom
import java.sql.{Blob, SQLException}
import javax.crypto.SecretKeyFactory
import javax.crypto.spec.PBEKeySpec
import javax.xml.bind.DatatypeConverter

import edu.cmu.cs.ls.keymaerax.bellerophon.{BTacticParser, BelleExpr, BelleProvable, SequentialInterpreter}
import _root_.edu.cmu.cs.ls.keymaerax.btactics.TactixLibrary
import _root_.edu.cmu.cs.ls.keymaerax.core._
import _root_.edu.cmu.cs.ls.keymaerax.hydra.ExecutionStepStatus.ExecutionStepStatus
import edu.cmu.cs.ls.keymaerax.lemma._
import _root_.edu.cmu.cs.ls.keymaerax.parser.{KeYmaeraXExtendedLemmaParser, KeYmaeraXParser, KeYmaeraXProblemParser, ProofEvidence}
import _root_.edu.cmu.cs.ls.keymaerax.tools.ToolEvidence
import edu.cmu.cs.ls.keymaerax.btactics.DerivedAxioms.LemmaID
import edu.cmu.cs.ls.keymaerax.core.{Formula, Provable, Sequent, SuccPos}

import scala.collection.immutable.Nil

//import Tables.TacticonproofRow
import scala.slick.jdbc.StaticQuery.interpolation
import scala.slick.driver.SQLiteDriver.simple._
import scala.slick.lifted.{ProvenShape, ForeignKeyQuery}

/**
 * Created by nfulton on 4/10/15.
 */
object SQLite {

  import Tables._

  val ProdDB: SQLiteDB = new SQLiteDB(DBAbstractionObj.dblocation)
  /** Use this for all unit tests that work with the database, so tests don't infect the production database */
  val TestDB: SQLiteDB = new SQLiteDB(DBAbstractionObj.testLocation)

  /** Stores lemmas in the Lemma table of the given database. */
  class UncachedSQLiteLemmaDB(db: SQLiteDB) extends LemmaDBBase {
    def readLemmas(ids: List[LemmaID]):Option[List[String]] = {
      db.getLemmas(ids.map(_.toInt))
    }

    def writeLemma(id: LemmaID, lemma:String) = {
      if(db.getLemma(id.toInt).nonEmpty)
        db.updateLemma(id.toInt, lemma)
      else {
        val createdId = db.createLemma()
        assert(createdId.toInt == id.toInt, "Cannot create a new lemma with a custom ID unless that ID happens to be the next one generated by the SQLite database.")
        db.updateLemma(createdId, lemma)
      }
    }

    def createLemma():LemmaID = db.createLemma().toString

    override def remove(name: String): Boolean = {
      db.deleteLemma(name.toInt)
    }

    override def deleteDatabase(): Unit = {
      db.deleteAllLemmas()
    }
  }

  def SQLiteLemmaDB (db: UncachedSQLiteLemmaDB) = new CachedLemmaDB(db)

  class SQLiteDB(val dblocation: String) extends DBAbstraction {
    val sqldb = Database.forURL("jdbc:sqlite:" + dblocation, driver = "org.sqlite.JDBC")
    val uncachedLemmaDB : UncachedSQLiteLemmaDB = new UncachedSQLiteLemmaDB(this)
    val lemmaDB = SQLiteLemmaDB(uncachedLemmaDB)
    private var currentSession:Session = null
    /* Statistics on the number of SQL operations performed in this session, useful for profiling. */
    private var nUpdates = 0
    private var nInserts = 0
    private var nSelects = 0

    implicit def session:Session = {
      if (currentSession == null || currentSession.conn.isClosed) {
        currentSession = sqldb.createSession()
        /* Enable write-ahead logging for SQLite - significantly improves write performance */
        sqlu"PRAGMA journal_mode = WAL".execute(currentSession)
        /* Note: Setting synchronous = NORMAL introduces some risk of database corruption during power loss. According
         * to official documentation, that risk is less than the risk of the hard drive failing completely, but we
         * should at least be aware that the risk exists. Initial testing showed this to be about 8 times faster, so
         * it seems worth the risk. */
        sqlu"PRAGMA synchronous = NORMAL".execute(currentSession)
        sqlu"VACUUM".execute(currentSession)
      }
      currentSession
    }

    private def ensureExists(location: String): Unit = {
      if (!new java.io.File(location).exists()) {
        cleanup(location)
      }
    }
    ensureExists(DBAbstractionObj.dblocation)
    ensureExists(DBAbstractionObj.testLocation)

    /* withTransaction is not thread-safe if you reuse connections, it will raise an exception saying we're in autocommit
     * mode when we shouldn't be. So only ever call withTransaction inside a synchronized block. */
    def synchronizedTransaction[T](f: => T)(implicit session:Session): T =
      synchronized {
        session.withTransaction(f)
    }

    private[SQLite] def createLemma(): Int = {
      synchronizedTransaction({
        (Lemmas.map(_.lemma) returning Lemmas.map(_._Id.get))
          .insert(None)
      })
    }

    private[SQLite] def updateLemma(lemmaId: Int, lemma:String): Unit = {
      synchronizedTransaction({
        Lemmas.filter(_._Id === lemmaId).map(_.lemma).update(Some(lemma))
      })
    }

    private[SQLite] def getLemma(lemmaId: Int): Option[String] = {
      getLemmas(List(lemmaId)) match {
        case Some(lemmas) => lemmas.headOption
        case None => None
      }
    }

    /** Allow retrieving lemmas in bulk to reduce the number of database queries */
    private[SQLite] def getLemmas(lemmaIds: List[Int]): Option[List[String]] = {
      synchronizedTransaction({
        if(Lemmas.length.run == 0) None
        try {
          val lemmaMap = Lemmas.map{case row => (row._Id.get, row.lemma.get)}.list.toMap
          Some(lemmaIds.map(lemmaMap(_)))
        } catch {
          case _:Exception => None
        }
      })
    }

    private[SQLite] def deleteLemma(lemmaId: Int): Boolean = {
      synchronizedTransaction({
        Lemmas.filter(_._Id === lemmaId).delete == 1
      })
    }

    private[SQLite] def deleteAllLemmas(): Unit = {
      synchronizedTransaction({
        Lemmas.delete
      })
    }

    override def syncDatabase():Unit = {
      sqlu"PRAGMA wal_checkpoint(FULL)".execute(session)
    }

    // Configuration
    override def getAllConfigurations: Set[ConfigurationPOJO] =
      synchronizedTransaction({
        nSelects = nSelects + 1
        Config.list.filter(_.configname.isDefined).map(_.configname.get).map(getConfiguration(_)).toSet
      })

    private def blankOk(x: Option[String]): String = x match {
      case Some(y) => y
      case None => ""
    }

    override def getModelList(userId: String): List[ModelPOJO] = {
      synchronizedTransaction({
        nSelects = nSelects + 1
        Models.filter(_.userid === userId).list.map(element => new ModelPOJO(element._Id.get, element.userid.get, element.name.get,
          blankOk(element.date), blankOk(element.filecontents),
          blankOk(element.description), blankOk(element.publink), blankOk(element.title), element.tactic, getNumProofs(element._Id.get)))
      })
    }

    private def getNumProofs(modelId: Int): Int = {
      Proofs.filter(_.modelid === modelId).length.run
    }

    private def configWithDefault(config: String, subconfig: String, default: Int): Int = {
      try {
        getConfiguration(config).config(subconfig).toInt
      } catch {case (_: NoSuchElementException) =>
        default
      }
    }
    override def createUser(username: String, password: String): Unit = {
      /* Store passwords as a salted hash. Allow configuring number of iterations
       * since we may conceivably want to change it after deployment for performance reasons */
      val iterations = configWithDefault("security", "passwordHashIterations", 10000)
      val saltLength = configWithDefault("security", "passwordSaltLength", 512)
      val (hash, salt) = Password.generateKey(password, iterations, saltLength)
      synchronizedTransaction({
        Users.map(u => (u.email.get, u.hash.get, u.salt.get, u.iterations.get))
          .insert((username, hash, salt, iterations))
        nInserts = nInserts + 1
        copyTutorialModels(username)
      })}

    private def copyTutorialModels(userId: String): Unit = {
      val tutorialModels = Models.filter(_._Id <= 14).list.map(element => new ModelPOJO(element._Id.get, element.userid.get, element.name.get,
        blankOk(element.date), blankOk(element.filecontents),
        blankOk(element.description), blankOk(element.publink), blankOk(element.title), element.tactic, getNumProofs(element._Id.get)))
      tutorialModels.foreach(m => createModel(userId, m.name, m.keyFile, m.date, Some(m.description), Some(m.pubLink), Some(m.title), m.tactic))
    }

    /**
      * Poorly named -- either update the config, or else insert an existing key.
      * But in Mongo it was just update, because of the nested documents thing.
      *
      * @param config
      */
    override def updateConfiguration(config: ConfigurationPOJO): Unit =
      synchronizedTransaction({
        config.config.foreach(kvp => {
          val key = kvp._1
          val value = kvp._2
          nSelects = nSelects + 1
          val configExists = Config.filter(c => c.configname === config.name && c.key === key).list.nonEmpty

          if (configExists) {
            val q = for {l <- Config if l.configname === config.name && l.key === key} yield l.value
            q.update(Some(value))
            nUpdates = nUpdates + 1
          }
          else {
            Config.map(c => (c.configname.get, c.key.get, c.value.get))
              .insert((config.name, key, value))
            nInserts = nInserts + 1
          }
        })
      })

    //Proofs and Proof Nodes
    override def getProofInfo(proofId: Int): ProofPOJO =
      synchronizedTransaction({
        val stepCount = nSteps(proofId)
        nSelects = nSelects + 1
        val list = Proofs.filter(_._Id === proofId)
          .list
          .map(p => new ProofPOJO(p._Id.get, p.modelid.get, blankOk(p.name), blankOk(p.description),
            blankOk(p.date), stepCount, p.closed.getOrElse(0) == 1))
        if (list.length > 1) throw new Exception("Duplicate proof " + proofId)
        else if (list.isEmpty) throw new Exception("Proof not found: " + proofId)
        else list.head
      })

    // Users
    override def userExists(username: String): Boolean =
      synchronizedTransaction({
        nSelects = nSelects + 1
        Users.filter(_.email === username).list.nonEmpty
      })


    override def getProofsForUser(userId: String): List[(ProofPOJO, String)] =
      synchronizedTransaction({
        val models = getModelList(userId)

        models.flatMap(model => {
          val modelName = model.name
          val proofs = getProofsForModel(model.modelId)
          proofs.map((_, modelName))
        })
      })

    override def checkPassword(username: String, password: String): Boolean =
      synchronizedTransaction({
        nSelects = nSelects + 1
        Users.filter(_.email === username).list.exists({case row =>
          val hash = Password.hash(password.toCharArray, row.salt.get.getBytes("UTF-8"), row.iterations.get)
          Password.hashEquals(hash, row.hash.get)
        })
      })

    override def updateProofInfo(proof: ProofPOJO): Unit =
      synchronizedTransaction({
        nSelects = nSelects + 1
        Proofs.filter(_._Id === proof.proofId).update(proofPojoToRow(proof))
        nUpdates = nUpdates + 1
      })

    private def proofPojoToRow(p: ProofPOJO): ProofsRow =
      new ProofsRow(_Id = Some(p.proofId), modelid = Some(p.modelId), name = Some(p.name)
        , description = Some(p.description), date =Some(p.date), closed = Some(if (p.closed) 1 else 0))

    private def sqliteBoolToBoolean(x: Int) = if (x == 0) false else if (x == 1) true else throw new Exception()

    //returns id of create object
    override def getProofsForModel(modelId: Int): List[ProofPOJO] =
      synchronizedTransaction({
        nSelects = nSelects + 1
        Proofs.filter(_.modelid === modelId).list.map(p => {
          val stepCount = nSteps(p._Id.get)
          val closed: Boolean = sqliteBoolToBoolean(p.closed.getOrElse(0))
          new ProofPOJO(p._Id.get, p.modelid.get, blankOk(p.name), blankOk(p.description), blankOk(p.date), stepCount, closed)
        })
      })

    def deleteExecution(executionId: Int) = synchronizedTransaction({
      val deletedExecutionSteps = Executionsteps.filter(_.executionid === executionId).delete == 1
      val deletedExecution = Tacticexecutions.filter(_._Id === executionId).delete == 1
      deletedExecutionSteps && deletedExecution
    })

    override def deleteProof(proofId: Int) =
      synchronizedTransaction({
        Tacticexecutions.filter(x => x.proofid === proofId).foreach(f => deleteExecution(f._Id.get))
        Proofs.filter(x => x._Id === proofId).delete == 1
      })

    //Models
    override def createModel(userId: String, name: String, fileContents: String, date: String,
                             description: Option[String] = None, publink: Option[String] = None,
                             title: Option[String] = None, tactic: Option[String] = None): Option[Int] =
      synchronizedTransaction({
        nSelects = nSelects + 1
        if (Models.filter(_.userid === userId).filter(_.name === name).list.isEmpty) {
          nInserts = nInserts + 1
          Some((Models.map(m => (m.userid.get, m.name.get, m.filecontents.get, m.date.get, m.description, m.publink, m.title, m.tactic))
            returning Models.map(_._Id.get))
            .insert(userId, name, fileContents, date, description, publink, title, tactic))
        }
        else None
      })

    override def createProofForModel(modelId: Int, name: String, description: String, date: String): Int =
      synchronizedTransaction({
        nInserts = nInserts + 2
        val proofId =
          (Proofs.map(p => ( p.modelid.get, p.name.get, p.description.get, p.date.get, p.closed.get))
            returning Proofs.map(_._Id.get))
            .insert(modelId, name, description, date, 0)
        Tacticexecutions.map(te => te.proofid.get).insert(proofId)
        proofId
      })

    override def getModel(modelId: Int): ModelPOJO =
      synchronizedTransaction({
        nSelects = nSelects + 1
        val models =
          Models.filter(_._Id === modelId)
            .list
            .map(m => new ModelPOJO(
              m._Id.get, m.userid.get, blankOk(m.name), blankOk(m.date), m.filecontents.get, blankOk(m.description),
              blankOk(m.publink), blankOk(m.title), m.tactic, getNumProofs(m._Id.get)
            ))
        if (models.length < 1) throw new Exception("getModel type should be an Option")
        else if (models.length == 1) models.head
        else throw new Exception("Primary keys aren't unique in models table.")
      })

    override def deleteModel(modelId: Int): Boolean =
      synchronizedTransaction({
        Models.filter(_._Id === modelId).delete
        Proofs.filter(_.modelid === modelId).list.map(prf => deleteProof(prf._Id.get))
        true
      })

    private def optToString[T](o: Option[T]) = o match {
      case Some(x) => Some(x.toString)
      case None => None
    }

    override def getConfiguration(configName: String): ConfigurationPOJO =
      synchronizedTransaction({
        nSelects = nSelects + 1
        val kvp = Config.filter(_.configname === configName)
          .filter(_.key.isDefined)
          .list
          .map(conf => (conf.key.get, blankOk(conf.value)))
          .toMap
        new ConfigurationPOJO(configName, kvp)
      })

    /**
      * Initializes a new database.
      */
    override def cleanup (): Unit = { cleanup(DBAbstractionObj.dblocation)}
    def cleanup(which: String): Unit = {
      val dbFile = this.getClass.getResourceAsStream("/keymaerax.sqlite")
      val target = new java.io.File(which)
      val targetStream = new FileOutputStream(target)
      targetStream.getChannel.transferFrom(Channels.newChannel(dbFile), 0, Long.MaxValue)
      targetStream.close()
      dbFile.close()
    }

    /** Creates a new execution and returns the new ID in tacticExecutions */
    override def createExecution(proofId: Int): Int =
      synchronizedTransaction({
        val executionId =
          (Tacticexecutions.map(te => te.proofid.get)
            returning Tacticexecutions.map(_._Id.get))
            .insert(proofId)
        nInserts = nInserts + 1
        executionId
      })

    /** Deletes a provable and all associated sequents / formulas */
    override def deleteProvable(provableId: Int): Boolean = ???

    /**
      * Adds an execution step to an existing execution
      *
      * @note Implementations should enforce additional invarants -- never insert when branches or alt orderings overlap.
      */
    override def addExecutionStep(step: ExecutionStepPOJO): Int = {
      val (branchOrder:Int, branchLabel) = (step.branchOrder, step.branchLabel) match {
        case (None, None) => (null, null)
        case (Some(order), None) => (order, null)
        case (None, Some(label)) => (null, label)
        case (Some(order), Some(label)) =>
          throw new Exception("execution steps cannot have both a branchOrder and a branchLabel")
      }
      synchronizedTransaction({
        val status = ExecutionStepStatus.toString(step.status)
        val steps =
          Executionsteps.map({case dbstep => (dbstep.executionid.get, dbstep.previousstep, dbstep.parentstep,
            dbstep.branchorder.get, dbstep.branchlabel.get, dbstep.alternativeorder.get, dbstep.status.get, dbstep.executableid.get,
            dbstep.inputprovableid, dbstep.resultprovableid, dbstep.localprovableid, dbstep.userexecuted.get, dbstep.childrenrecorded.get,
            dbstep.rulename.get)
          }) returning Executionsteps.map(es => es._Id.get)
        val stepId = steps
            .insert((step.executionId, step.previousStep, step.parentStep, branchOrder, branchLabel,
              step.alternativeOrder, status, step.executableId, step.inputProvableId, step.resultProvableId,
              step.localProvableId, step.userExecuted.toString, false.toString, step.ruleName))
        nInserts = nInserts + 1
        stepId
      })
    }

    override def addAlternative(alternativeTo: Int, inputProvable: Provable, trace:ExecutionTrace):Unit = {
      def get(stepId: Int) = {
        Executionsteps.filter(_._Id === stepId).list match {
          case Nil => throw new Exception("Execution step not found")
          case step :: _ => step
        }
      }
      val oldStep = get(alternativeTo)
      def addSteps(prev: Option[Int], globalProvable:Provable, steps:List[ExecutionStep]): Unit = {
        if (steps.nonEmpty) {
          val thisStep = steps.head
          val thisPOJO = get(thisStep.stepId)
          val localProvable = getProvable(thisPOJO.localprovableid.get).provable
          val outputProvable = globalProvable(localProvable, thisStep.branch)
          val newStep = new ExecutionStepPOJO(None, oldStep.executionid.get, prev, None, Some(thisStep.branch),
            None, oldStep.alternativeorder.get + 1, ExecutionStepStatus.fromString(thisPOJO.status.get), thisPOJO.executableid.get,
            None, None, thisPOJO.localprovableid, thisPOJO.userexecuted.get.toBoolean, thisPOJO.rulename.get)
          val newId = addExecutionStep(newStep)
          addSteps(Some(newId), outputProvable, steps.tail)
        }
      }
      if(trace.steps.isEmpty) {
        // Insert a null tactic with a higher alternative order
        val nilExecutable = addBelleExpr(TactixLibrary.nil)
        val localConclusion = inputProvable.subgoals(0)
        // Generate a no-op local provable whose conclusion matches with the current state of the proof.
        val localProvable = Provable.startProof(localConclusion)
        val newLocalProvableID = createProvable(localProvable)
        val step = new ExecutionStepPOJO(None, oldStep.executionid.get, oldStep.previousstep, None, Some(0), None,
          oldStep.alternativeorder.get + 1, ExecutionStepStatus.Finished, nilExecutable, oldStep.inputprovableid,
          oldStep.inputprovableid, Some(newLocalProvableID), false, "nil")
        addExecutionStep(step)
      } else {
        addSteps(oldStep.previousstep, inputProvable, trace.steps)
      }
    }

    /** Adds a Bellerophon expression as an executable and returns the new executableId */
    override def addBelleExpr(expr: BelleExpr): Int =
      synchronizedTransaction({
        val executableId =
          (Executables.map({case exe => (exe.belleexpr) })
            returning Executables.map(_._Id.get))
          .insert(Some(expr.prettyString))
        nInserts = nInserts + 1
        executableId
      })

    /** Stores a Provable in the database and returns its ID */
    override def createProvable(p: Provable): Int = {
      synchronizedTransaction({
        val lemma = Lemma(p, Lemma.requiredEvidence(p, List(new ToolEvidence(List("input" -> p.prettyString, "output" -> "true")))))
        uncachedLemmaDB.add(lemma).toInt
      })
    }

    /** Returns the executable with ID executableId */
    override def getExecutable(executableId: Int): ExecutablePOJO = {
      getExecutables(List(executableId)).head
    }

    /** Allow retrieving executables in bulk to reduce the number of database queries. */
    def getExecutables(executableIds: List[Int]): List[ExecutablePOJO] =
      synchronizedTransaction({
        nSelects = nSelects + 1
        val executableMap =
          Executables.map(exe => (exe._Id.get, exe.belleexpr.get))
          .list
          .map{case (id, expr) => (id, ExecutablePOJO(id, expr))}
          .foldLeft(Map.empty[Int,ExecutablePOJO]){case (acc, (id, exe)) => acc.+((id, exe))}

        try {
          executableIds.map{case id => executableMap(id)}
        } catch {
          case _:Exception => throw new ProverException("getExecutable type should be an Option")
        }
      })

    /** Use escape hatch in prover core to create a new Provable */
    override def getProvable(lemmaId: Int): ProvablePOJO = {
      loadProvables(List(lemmaId)).head
    }

    def loadProvables(lemmaIds: List[Int]): List[ProvablePOJO] = {
      lemmaDB.get(lemmaIds.map(_.toString)) match {
        case None => throw new Exception (" No lemma for one of these IDs: " + lemmaIds)
        case Some(lemmas) => lemmas.zipWithIndex.map{case (lemma, id) => new ProvablePOJO(id, lemma.fact)}
      }
    }

    /** Rerun all execution steps to generate a provable for the current state of the proof
      * Assumes the execution starts with a trivial provable (one subgoal, which is the same
      * as the conclusion)
      *
      * This is only for testing purposes. If you need the last provable of an execution,trace,
      * you should use getExecutionTrace(id).lastProvable
      * */
    private def regenerate(proofId: Int): Provable = {
      val trace = getExecutionTrace(proofId)
      val inputProvable = Provable.startProof(trace.conclusion)
      val initialProvable = Provable.startProof(inputProvable.conclusion)
      def run(p: Provable, t:BelleExpr): Provable =
        SequentialInterpreter(Nil)(t,BelleProvable(p)) match {
          case BelleProvable(pr, _) => pr
        }
      def loadTactic(id: Int): BelleExpr = BTacticParser(getExecutable(id).belleExpr).get
      trace.steps.foldLeft(initialProvable)({case (provable, currStep) =>
          run(provable, loadTactic(currStep.executableId))
        })
      initialProvable
    }

    private def nSteps(proofId: Int): Int = {
      getTacticExecution(proofId) match {
        case Some(execution) => proofSteps(execution).size
        case None => 0
      }
    }

    override def addAgendaItem(proofId: Int, initialProofNode: Int, displayName:String): Int = {
      synchronizedTransaction({
        (Agendaitems.map({case item => (item.proofid.get, item.initialproofnode.get, item.displayname.get)})
          returning Agendaitems.map(_._Id.get))
          .insert(proofId, initialProofNode, displayName)
      })
    }

    override def updateAgendaItem(item:AgendaItemPOJO) = {
      synchronizedTransaction({
        Agendaitems.filter(_._Id === item.itemId)
          .map({case dbitem => (dbitem.proofid.get, dbitem.initialproofnode.get, dbitem.displayname.get)})
          .update((item.proofId, item.initialProofNode, item.displayName))
      })
    }

    override def agendaItemsForProof(proofId: Int): List[AgendaItemPOJO] = {
      synchronizedTransaction({
        Agendaitems.filter(_.proofid === proofId)
        .list
        .map({case item => AgendaItemPOJO(item._Id.get, item.proofid.get, item.initialproofnode.get, item.displayname.get)})
      })
    }

    override def getAgendaItem(proofId: Int, initialProofNode: Int): Option[AgendaItemPOJO] = {
      synchronizedTransaction({
        Agendaitems.filter{row => row.proofid === proofId && row.initialproofnode === initialProofNode}
          .list
          .map({case item => AgendaItemPOJO(item._Id.get, item.proofid.get, item.initialproofnode.get, item.displayname.get)})
          .headOption
      })
    }

    /** Updates an executable step */
    override def updateExecutionStep(executionStepId: Int, step: ExecutionStepPOJO): Unit = {
      synchronizedTransaction({
        nSelects = nSelects + 1
        nUpdates = nUpdates + 1
        Executionsteps.filter(_._Id === executionStepId)
        .map({case dbstep => (dbstep.executionid.get, dbstep.previousstep, dbstep.parentstep,
          dbstep.branchorder, dbstep.branchlabel, dbstep.alternativeorder.get, dbstep.status.get, dbstep.executableid.get,
          dbstep.inputprovableid, dbstep.resultprovableid, dbstep.localprovableid, dbstep.userexecuted.get, dbstep.childrenrecorded.get,
          dbstep.rulename.get)
        })
        .update((step.executionId, step.previousStep, step.parentStep, step.branchOrder, step.branchLabel,
          step.alternativeOrder, ExecutionStepStatus.toString(step.status), step.executableId, step.inputProvableId, step.resultProvableId,
          step.localProvableId, step.userExecuted.toString, false.toString, step.ruleName))
      })
    }

    private def sortFormulas(fromAnte: Boolean, formulas: List[SequentFormulaPOJO]): List[Formula] = {
      import edu.cmu.cs.ls.keymaerax.parser.StringConverter._
      val relevant = formulas.filter({ case formula => fromAnte == formula.isAnte })
      val sorted = relevant.sortWith({ case (f1, f2) => f1.index > f2.index })
      sorted.map({ case formula => formula.formulaStr.asFormula })
    }

    def printStats(): Unit = {
      println("Updates: " + nUpdates + " Inserts: " + nInserts + " Selects: " + nSelects)
    }

    def proofSteps(executionId: Int): List[ExecutionStepPOJO] = {
      synchronizedTransaction({
        var steps = Executionsteps.filter({case row => row.executionid === executionId &&
          row.status === ExecutionStepStatus.toString(ExecutionStepStatus.Finished)}).list
        var prevId: Option[Int] = None
        var revResult: List[ExecutionStepPOJO] = Nil
        /* The Executionsteps table may contain many alternate histories for the same execution. In order to reconstruct
        * the current state of the world, we must pick the most recent alternative at every opportunity.*/
        steps = steps.sortWith({case (x, y) => y.alternativeorder.get < x.alternativeorder.get})
        while(steps != Nil) {
          val (headSteps, tailSteps) = steps.partition({step => step.previousstep == prevId})
          if (headSteps == Nil)
            return revResult.reverse
          val head = headSteps.head
          revResult =
            new ExecutionStepPOJO(head._Id, head.executionid.get, head.previousstep, head.parentstep,
              head.branchorder, head.branchlabel, head.alternativeorder.get, ExecutionStepStatus.fromString(head.status.get),
              head.executableid.get, head.inputprovableid, head.resultprovableid, head.localprovableid, head.userexecuted.get.toBoolean,
              head.rulename.get)::revResult
          prevId = head._Id
          steps = tailSteps
        }
        revResult.reverse
      })
    }

    private def getProofConclusion(proofId: Int): Sequent = {
      val modelId = getProofInfo(proofId).modelId
      val model = getModel(modelId)
      KeYmaeraXProblemParser(model.keyFile) match {
        case fml:Formula => Sequent(collection.immutable.IndexedSeq(), collection.immutable.IndexedSeq(fml))
        case _ => throw new Exception("Failed to parse model for proof " + proofId + " model " + modelId)
      }
    }

    private def getTacticExecution(proofId: Int): Option[Int] =
      synchronizedTransaction({
          val executionIds =
            Tacticexecutions.filter(_.proofid === proofId)
              .list
              .map({ case row => row._Id.get })
          if (executionIds.length < 1) None
          else if (executionIds.length == 1) Some(executionIds.head)
          else throw new Exception("Primary keys aren't unique in executions table.")
        })

    private def zipTrace(executionSteps: List[ExecutionStepPOJO], executables: List[ExecutablePOJO], inputProvable:Provable, localProvables: List[Provable]): List[ExecutionStep] = {
      (executionSteps, executables, localProvables) match {
        case (step::steps, exe:: exes, localProvable::moreProvables) =>
          val output = inputProvable(localProvable, step.branchOrder.get)
          ExecutionStep(step.stepId.get, inputProvable, Some(localProvable), step.branchOrder.get, step.alternativeOrder, step.ruleName, step.executableId, step.userExecuted)  ::
            zipTrace(steps, exes, output, moreProvables)
        case (Nil, Nil, Nil) => Nil
        case _ => throw new ProverException("Bug in zipTrace")
      }
    }

    override def getExecutionSteps(executionId: Int): List[ExecutionStepPOJO] = proofSteps(executionId)

    override def getExecutionTrace(proofId: Int): ExecutionTrace = {
      /* This method has proven itself to be a resource hog, so this implementation attempts to minimize the number of
         DB calls. */
      getTacticExecution(proofId) match {
        case Some(executionId) =>
          val steps = proofSteps(executionId)
          if (steps.isEmpty) {
            val conclusion = getProofConclusion(proofId)
            ExecutionTrace(proofId.toString, executionId.toString, conclusion, Nil)
          } else {
            val provableIds = steps.map { case step => step.localProvableId.get }
            val executableIds = steps.map { case step => step.executableId }
            val provables = loadProvables(provableIds).map(_.provable)
            val conclusion = provables.head.conclusion
            val initProvable = Provable.startProof(conclusion)
            val executables = getExecutables(executableIds)
            val traceSteps = zipTrace(steps, executables, initProvable, provables)
            ExecutionTrace(proofId.toString, executionId.toString, conclusion, traceSteps)
          }
        case None =>
          val conclusion = getProofConclusion(proofId)
          //@todo is execution ID really unused so far?
          ExecutionTrace(proofId.toString, null, conclusion, Nil)
      }
    }

    override def getInvariants(modelId: Int): Map[Expression, Formula] = {
      val model = getModel(modelId)
      var invariants: Map[Expression, Formula] = Map.empty
      KeYmaeraXParser.setAnnotationListener{case (program, formula) =>
        invariants = invariants.+((program, formula))
      }
      KeYmaeraXProblemParser(model.keyFile)
      invariants
    }

  }
}